# Taken From: https://code.google.com/p/dolphin-emu/source/browse/CMakeTests/FindSDL2.cmake

FIND_PATH(SDL2_INCLUDE_DIR SDL.h
  ~/Library/Frameworks
  /Library/Frameworks
)
MESSAGE("SDL2_INCLUDE_DIR is ${SDL2_INCLUDE_DIR}")

FIND_LIBRARY(SDL2_LIBRARY
  NAMES SDL2
)
MESSAGE("SDL2_LIBRARY is ${SDL2_LIBRARY}")


FIND_PATH(SDL2_IMAGE_INCLUDE_DIR SDL_image.h
  ~/Library/Frameworks
  /Library/Frameworks
)
MESSAGE("SDL2_IMAGE_INCLUDE_DIR is ${SDL2_IMAGE_INCLUDE_DIR}")

FIND_LIBRARY(SDL2_IMAGE_LIBRARY
  NAMES SDL2_image
)
MESSAGE("SDL2_IMAGE_LIBRARY is ${SDL2_IMAGE_LIBRARY}")


FIND_PATH(SDL2_TTF_INCLUDE_DIR SDL_ttf.h
  ~/Library/Frameworks
  /Library/Frameworks
)
MESSAGE("SDL2_TTF_INCLUDE_DIR is ${SDL2_TTF_INCLUDE_DIR}")

FIND_LIBRARY(SDL2_TTF_LIBRARY
  NAMES SDL2_ttf
)
MESSAGE("SDL2_TTF_LIBRARY is ${SDL2_TTF_LIBRARY}")


FIND_PATH(SDL2_MIXER_INCLUDE_DIR SDL_mixer.h
  ~/Library/Frameworks
  /Library/Frameworks
)
MESSAGE("SDL2_MIXER_INCLUDE_DIR is ${SDL2_MIXER_INCLUDE_DIR}")

FIND_LIBRARY(SDL2_MIXER_LIBRARY
  NAMES SDL2_mixer
)
MESSAGE("SDL2_MIXER_LIBRARY is ${SDL2_MIXER_LIBRARY}")